name: Check if site builds

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.8.0]

    steps:
      - name: Checkout site
        id: checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        id: setup_node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Build site
        id: build
        run: |
          yarn install
          yarn prebuild
          yarn build
